import os
import gc
import torch
import numpy as np
import soundfile as sf
from flask import Flask, request, jsonify

app = Flask(__name__)

# Lazy load Kokoro model
KOKORO_PIPELINE = None

def get_pipeline():
    global KOKORO_PIPELINE
    if KOKORO_PIPELINE is None:
        from kokoro import KPipeline
        print("[CONTAINER - KOKORO] Loading Kokoro KPipeline...")
        device = "cuda" if torch.cuda.is_available() else "cpu"
        # English is default, but it can handle multiple languages
        KOKORO_PIPELINE = KPipeline(lang_code='a', device=device)
    return KOKORO_PIPELINE

def flush_memory():
    gc.collect()
    if torch.cuda.is_available():
        torch.cuda.empty_cache()
        torch.cuda.synchronize()

@app.route("/synthesize", methods=["POST"])
def synthesize():
    data = request.get_json(force=True) or {}
    text = data.get("text", "")
    voice = data.get("voice", "af_bella") # Default English female voice
    speed = float(data.get("speed", 1.0))
    output_path = data.get("output_path", "/content/kokoro_speech.wav")

    if not text:
        return jsonify({"error": "text is required"}), 400

    try:
        pipeline = get_pipeline()
        
        # Generator yields (graphemes, phonemes, audio)
        generator = pipeline(text, voice=voice, speed=speed, split_pattern=r'\n+')
        
        all_audio = []
        for _, _, audio in generator:
            if audio is not None:
                all_audio.append(audio)
                
        if not all_audio:
            raise RuntimeError("No audio was generated by Kokoro")
            
        # Concatenate audio segments
        combined_audio = np.concatenate(all_audio)
        
        # Save audio file
        sf.write(output_path, combined_audio, 24000) # Kokoro generates at 24000Hz
        
        return jsonify({"status": "success", "output_path": output_path}), 200

    except Exception as e:
        flush_memory()
        return jsonify({"status": "error", "message": str(e)}), 500

@app.route("/health", methods=["GET"])
def health():
    return jsonify({"status": "healthy"}), 200

if __name__ == "__main__":
    app.run(host="0.0.0.0", port=5000)
