"""Generate barrel index.ts for src/services/ and update import paths.

Safe approach: only re-export services imported by 3+ files (12 services).
Handles naming conflicts with aliased imports.
"""
import os, re
from collections import defaultdict

src_dir = os.path.join(os.path.dirname(__file__), '..', 'src')
svc_dir = os.path.join(src_dir, 'services')

# Step 1: Find all files importing from individual service files
imports = defaultdict(list)
for root, dirs, files in os.walk(src_dir):
    for f in files:
        if not f.endswith(('.ts', '.tsx')):
            continue
        fpath = os.path.join(root, f)
        with open(fpath, 'r', encoding='utf-8', errors='ignore') as fh:
            content = fh.read()
        for m in re.finditer(
            r"""from\s+['"](\.[/.]*(?:/services)/([^'"]+))['"]""",
            content,
        ):
            target = m.group(2).replace('.ts', '').replace('.js', '')
            if target == 'index':
                continue
            rel = os.path.relpath(fpath, src_dir).replace('\\', '/')
            imports[target].append((rel, m.group(1), content, f, fpath))

# Step 2: Find naming conflicts in candidate services
candidates = {
    svc: consumers
    for svc, consumers in sorted(imports.items(), key=lambda x: len(x[1]), reverse=True)
    if len(consumers) >= 3
}

print(f'Candidate services for barrel: {list(candidates.keys())}')
print()

# Step 3: Check for conflicts within candidate set
all_exports = {}
conflicts = set()
for svc in candidates:
    fname = f'{svc}.ts' if os.path.exists(os.path.join(svc_dir, f'{svc}.ts')) else f'{svc}.js'
    fpath = os.path.join(svc_dir, fname)
    if not os.path.exists(fpath):
        # Try nested like crewai/writerTiers
        fpath = os.path.join(svc_dir, *svc.split('/'))
        fpath_ts = fpath + '.ts'
        fpath_js = fpath + '.js'
        if os.path.exists(fpath_ts):
            fpath = fpath_ts
        elif os.path.exists(fpath_js):
            fpath = fpath_js
        else:
            print(f'  SKIP: {svc} not found')
            continue
    with open(fpath, 'r', encoding='utf-8', errors='ignore') as fh:
        content = fh.read()
    names = []
    for m in re.finditer(r'export\s+(?:const|function|class|interface|type|enum|default\s+(?:class|function|const))\s+(\w+)', content):
        names.append(m.group(1))
    for m in re.finditer(r'export\s*\{\s*([^}]+)\s*\}', content):
        for n in re.finditer(r'(\w+)', m.group(1)):
            names.append(n.group(1))
    for name in names:
        if name in all_exports:
            conflicts.add(name)
            print(f'  CONFLICT: {name} in {svc} (also in {all_exports[name]})')
        all_exports[name] = svc

# Step 4: Generate index.ts content (only non-conflicted from candidate set)
barrel_lines = []
for svc in sorted(candidates.keys()):
    mod_name = svc.replace('/', '__')
    if mod_name.startswith('crewai__'):
        mod_name = mod_name.replace('crewai__', '')
    barrel_lines.append(f"export * from './{svc}.js';")

barrel_content = (
    '// Auto-generated barrel index for commonly imported services.\n'
    + '// Generated by scripts/generate_barrel.py\n'
    + '// Do not edit manually — conflicts are explicitly guarded.\n\n'
    + '\n'.join(barrel_lines)
    + '\n'
)

idx_path = os.path.join(svc_dir, 'index.ts')
with open(idx_path, 'w', encoding='utf-8') as fh:
    fh.write(barrel_content)

print(f'\n=== Generated index.ts ===')
print(f'  File: {idx_path}')
print(f'  {len(barrel_lines)} re-exports')
if conflicts:
    print(f'  ⚠️  {len(conflicts)} conflicts found, skipped from barrel: {sorted(conflicts)}')

# Step 5: Show what to change (don't auto-apply, too risky)
print(f'\n=== Analysis complete ===')
print(f'  Next step: update {sum(len(v) for v in imports.values())} import statements in consumer files')
print(f'  Manual review recommended before applying.')
