/**
 * ngrok kurulum sihirbazı
 * ------------------------
 * Playwright ile ngrok.com dashboard'unu açar, kullanıcının giriş
 * yapmasını bekler, authtoken'ı okur ve .env dosyasına yazar.
 *
 * Kullanım: npm run setup-ngrok
 */
const { chromium } = require('playwright');
const fs = require('fs');
const path = require('path');

(async () => {
  console.log('🚀 ngrok kurulum sihirbazı başlatılıyor...');
  console.log('Tarayıcı açılacak — ngrok hesabınıza giriş yapın.\n');

  let browser;
  try {
    browser = await chromium.launch({ headless: false });
    const context = await browser.newContext();
    const page = await context.newPage();

    // Go to ngrok dashboard
    await page.goto('https://dashboard.ngrok.com/get-started/your-authtoken', {
      waitUntil: 'domcontentloaded',
      timeout: 60_000
    });
    console.log('📍 Lütfen ngrok hesabınıza giriş yapın...');
    console.log('   (Bu pencereyi kapatmayın — giriş yapıldıktan sonra token otomatik alınacak.)\n');

    // Wait for the authtoken to be visible (user must log in first)
    // Common selectors ngrok has used historically:
    //   - code.ngrok-authtoken
    //   - [data-test="authtoken"]
    //   - pre with the token inside
    const tokenSelector = [
      'code.ngrok-authtoken',
      '[data-test="authtoken"]',
      'pre.ngrok-authtoken',
      'pre:has-text("2")' // ngrok tokens start with "2" — last-resort heuristic
    ].join(', ');

    let tokenEl = null;
    try {
      await page.waitForSelector(tokenSelector, { timeout: 300_000 });
      tokenEl = await page.locator(tokenSelector).first();
    } catch (waitErr) {
      throw new Error('Authtoken bulunamadı (5 dk içinde). Giriş yaptığınızdan emin olun.');
    }

    const token = (await tokenEl.textContent() || '').trim();
    if (!token || token.length < 20) {
      throw new Error('Token okunamadı veya geçersiz format (çok kısa).');
    }
    // ngrok tokens look like: 2abcDefGhi1234567890_xyzAbc
    if (!/^[0-9A-Za-z_]+$/.test(token)) {
      console.warn('⚠️ Token beklenmedik karakterler içeriyor — yine de yazılıyor.');
    }

    console.log(`✓ Token alındı: ${token.substring(0, 8)}...${token.substring(token.length - 4)}`);

    // Write to .env
    const envPath = path.join(__dirname, '..', '.env');
    let envContent = '';
    if (fs.existsSync(envPath)) {
      envContent = fs.readFileSync(envPath, 'utf-8');
    } else {
      // Start with a header so the file is recognizable
      envContent = '# AI-Publisher .env — generated by scripts/setup-ngrok.js\n';
    }

    // Update or add NGROK_TOKEN
    if (/^NGROK_TOKEN\s*=/m.test(envContent)) {
      envContent = envContent.replace(/^NGROK_TOKEN\s*=.*$/m, `NGROK_TOKEN=${token}`);
    } else {
      // Ensure a blank line before appending
      if (envContent && !envContent.endsWith('\n')) envContent += '\n';
      envContent += `NGROK_TOKEN=${token}\n`;
    }

    fs.writeFileSync(envPath, envContent, 'utf-8');
    console.log(`✓ .env dosyasına yazıldı: ${envPath}`);
    console.log('\n🎉 Kurulum tamamlandı! Sunucuyu yeniden başlatabilirsiniz:');
    console.log('   npm run dev\n');
  } catch (err) {
    console.error('\n❌ Hata:', err.message);
    if (err.message && err.message.includes('Executable doesn\'t exist')) {
      console.error('\n💡 Playwright tarayıcıları kurulu değil. Çalıştırın:');
      console.error('   npx playwright install chromium\n');
    }
    process.exitCode = 1;
  } finally {
    if (browser) {
      try { await browser.close(); } catch {}
    }
  }
})();
